-- Schema is provided at runtime via RUNSQLSTM SETVAR
SET SCHEMA &LIB_STG;

TRUNCATE TABLE RAC_STG_VALID;
TRUNCATE TABLE RAC_STG_REJECTS;

-- Simple parsing example: assume CSV format 'id,amount'
INSERT INTO RAC_STG_VALID (ID, AMOUNT)
SELECT CAST(SUBSTRING(RAW_LINE, 1, LOCATE(',', RAW_LINE) - 1) AS INT),
       CAST(SUBSTRING(RAW_LINE, LOCATE(',', RAW_LINE) + 1) AS DECIMAL(9,2))
FROM RAC_STG_IN
WHERE LOCATE(',', RAW_LINE) > 0
  AND REGEXP_LIKE(SUBSTRING(RAW_LINE, 1, LOCATE(',', RAW_LINE) - 1), '^[0-9]+$')
  AND REGEXP_LIKE(SUBSTRING(RAW_LINE, LOCATE(',', RAW_LINE) + 1), '^-?[0-9]+(\\.[0-9]+)?$');

INSERT INTO RAC_STG_REJECTS (RAW_LINE, REASON)
SELECT si.RAW_LINE, 'PARSE_ERROR'
FROM RAC_STG_IN si
LEFT JOIN RAC_STG_VALID sv
  ON sv.ID = CAST(SUBSTRING(si.RAW_LINE, 1, LOCATE(',', si.RAW_LINE) - 1) AS INT)
WHERE sv.ID IS NULL;

-- Update existing rows then insert new ones to avoid MERGE for compatibility
UPDATE RAC_SHADOW_PAYROLL T
SET AMOUNT = (SELECT S.AMOUNT FROM RAC_STG_VALID S WHERE S.ID = T.ID)
WHERE T.ID IN (SELECT ID FROM RAC_STG_VALID);

INSERT INTO RAC_SHADOW_PAYROLL (ID, AMOUNT)
SELECT S.ID, S.AMOUNT
FROM RAC_STG_VALID S
LEFT JOIN RAC_SHADOW_PAYROLL T ON T.ID = S.ID
WHERE T.ID IS NULL;

INSERT INTO RAC_RUN_LOG (STATUS)
VALUES ('SUCCESS');
