-- Validate, transform and merge into shadow tables. Uses ${LIB_STG} variable.
SET SCHEMA ${LIB_STG};

-- Reset staging tables
DELETE FROM RAC_STG_VALID;
DELETE FROM RAC_STG_REJECTS;

-- Simple parsing example: assume CSV format 'id,amount'
INSERT INTO RAC_STG_VALID (ID, AMOUNT)
SELECT TRY_CAST(SUBSTRING(RAW_LINE, 1, LOCATE(',', RAW_LINE) - 1) AS INT),
       TRY_CAST(SUBSTRING(RAW_LINE, LOCATE(',', RAW_LINE) + 1) AS DECIMAL(9,2))
FROM RAC_STG_IN
WHERE RAW_LINE LIKE '%,%'
  AND TRY_CAST(SUBSTRING(RAW_LINE, 1, LOCATE(',', RAW_LINE) - 1) AS INT) IS NOT NULL
  AND TRY_CAST(SUBSTRING(RAW_LINE, LOCATE(',', RAW_LINE) + 1) AS DECIMAL(9,2)) IS NOT NULL;

INSERT INTO RAC_STG_REJECTS (RAW_LINE, REASON)
SELECT RAW_LINE, 'PARSE_ERROR'
FROM RAC_STG_IN si
WHERE NOT EXISTS (
    SELECT 1 FROM RAC_STG_VALID sv WHERE sv.ID = TRY_CAST(SUBSTRING(si.RAW_LINE, 1, LOCATE(',', si.RAW_LINE) - 1) AS INT)
);

MERGE INTO RAC_SHADOW_PAYROLL T
USING RAC_STG_VALID S
ON T.ID = S.ID
WHEN MATCHED THEN UPDATE SET AMOUNT = S.AMOUNT
WHEN NOT MATCHED THEN INSERT (ID, AMOUNT) VALUES (S.ID, S.AMOUNT);

INSERT INTO RAC_RUN_LOG (STATUS)
VALUES ('SUCCESS');
