-- Variables prefixed with & are substituted at runtime via RUNSQLSTM SETVAR.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

CREATE SCHEMA IF NOT EXISTS &LIB_STG;

CREATE TABLE IF NOT EXISTS &LIB_STG.RAC_STG_IN (
    RAW_LINE VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS &LIB_STG.RAC_STG_VALID (
    ID INT NOT NULL,
    AMOUNT DECIMAL(9,2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS &LIB_STG.RAC_STG_REJECTS (
    RAW_LINE VARCHAR(512),
    REASON VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS &LIB_STG.RAC_SHADOW_PAYROLL (
    ID INT PRIMARY KEY,
    AMOUNT DECIMAL(9,2)
);

CREATE TABLE IF NOT EXISTS &LIB_STG.RAC_RUN_LOG (
    RUN_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(7),
    HASH CHAR(64)
);
