-- Setup staging schema and tables. Uses &LIB_STG variable.
CREATE SCHEMA IF NOT EXISTS &LIB_STG;

SET SCHEMA &LIB_STG;

CREATE TABLE IF NOT EXISTS STG_IN (
    RAW_LINE VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS STG_VALID (
    ID INT NOT NULL,
    AMOUNT DECIMAL(9,2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS STG_REJECTS (
    RAW_LINE VARCHAR(512),
    REASON VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS SHADOW_PAYROLL (
    ID INT PRIMARY KEY,
    AMOUNT DECIMAL(9,2)
);

CREATE TABLE IF NOT EXISTS RUN_LOG (
    RUN_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(7),
    HASH CHAR(64)
);
