-- Library is provided at runtime via RUNSQLSTM SETVAR
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DROP SCHEMA IF EXISTS &LIB_STG CASCADE;
