name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OS packages
        run: sudo apt-get update && sudo apt-get install -y python3-tk openssh-client
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt flake8
      - name: Ruff
        run: ruff check .
      - name: Flake8
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Install OS packages
        run: sudo apt-get update && sudo apt-get install -y python3-tk openssh-client
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt pytest
      - name: Run tests
        env:
          HOST: localhost
          USER: test
          PASSWORD: test
          REMOTE_DIR: /tmp
          LIB: QGPL
          PROGRAM: PGM
          USE_SSH: '1'
        run: pytest
