name: coverage
on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  python-coverage:
    name: Python coverage → Codacy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov coverage

      - name: Run tests & build Cobertura report
        run: pytest --maxfail=1 --disable-warnings --cov=. --cov-report=xml:coverage.xml

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
